# Generated by Django 2.2.2 on 2019-06-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50)),
                ('razonSocial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dteEmision', models.DateTimeField()),
                ('dteTipo', models.CharField(max_length=50)),
                ('dteFolio', models.IntegerField()),
                ('emisorID', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='saveInvoices.Company')),
                ('receptorID', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='saveInvoices.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('txt', models.CharField(max_length=100)),
                ('dte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saveInvoices.Dte')),
            ],
        ),
    ]
