# Generated by Django 2.2 on 2019-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveInvoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte',
            name='dteEmision',
            field=models.DateTimeField(),
        ),
    ]
