# Generated by Django 2.2.2 on 2019-06-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saveInvoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte',
            name='emisorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='saveInvoices.Company'),
        ),
        migrations.AlterField(
            model_name='dte',
            name='receptorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='saveInvoices.Company'),
        ),
    ]
